### ISSUE TITLE
Compilation with CUDA fails (Linux; GCC)

### ISSUE THREAD

**Issue by 4re** [DeadSix27/waifu2x-converter-cpp#46]
Here is the build log https://gist.githubusercontent.com/4re/45b8a76ad38abee2cc4fbe636182f130/raw/002930fe8c69e28ce0333438052bbedfb109d0f0/error.log

**Comment by DeadSix27** [comment]
see: https://github.com/DeadSix27/waifu2x-converter-cpp/issues/35

**Comment by 4re** [comment]
I think this is not the same bug. I was getting #35 as well but it looks like I have a different one in addition.

Just to be safe about it I applied all the changes proposed in #35 to no avail.

The relevant lines in the log are:
```
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
```
[This](https://gist.githubusercontent.com/4re/b126baeb6ed512573f8726068c456138/raw/a9bac2e1009abd4c02a5451dcf7017c3c81f9402/error.log) is the log with the patch applied.

```
gcc versión 6.4.0 (Gentoo 6.4.0 p1.1)
cmake version 3.9.6
opencv_version 3.3.0
nvidia-cuda-toolkit-9.0.176
```

**Comment by 4re** [comment]
And this is the patch [cuda.diff](https://gist.github.com/4re/736fb4b326ac7d51ba05a426ee2643f6) just in case.

**Comment by DeadSix27** [comment]
Some of your issues appear here: https://github.com/caffe2/caffe2/issues/1194

he said that "CUDA package on Arch Linux received a fix to be able to work with glibc 2.26. It works nice for me after the fix."

To me it looks like `/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"`

Indicating its not waifu2x's problem..


`/var/tmp/portage/media-libs/waifu2x-converter-cpp-5.2/work/waifu2x-converter-cpp-5.2/src/modelHandler_CUDA.cu(480): warning: function "__shfl_down(float, unsigned int, int)"`

Is just a deprecation warning though

**Comment by DeadSix27** [comment]
also check this out: https://www.xpra.org/trac/ticket/1600

**Comment by 4re** [comment]
I see, thank you for pointing me in the right direction. In the end, it is a CUDA bug and seeing as they ignored it from their 8.0 release until now I see little hope in them.

**Comment by DeadSix27** [comment]
@4re I am not sure tbh Some ppl got this to compile fine with cuda 9.0 I think, did you try that?

**Comment by 4re** [comment]
I patched my system files with the changes suggested and it compiled and worked fine.
I tested it and I can correctly process images with the CUDA backend.

I'm maintaining a Gentoo overlay and wanted to offer your package with proper CUDA support, but seeing as I would have to provide patched builds for `sys-libs/glibc` and `nvidia-cuda-toolkit` (if I want it to work with GCC 7), it is just too ugly and bothersome. Also, I don't think this would appeal to the users.

I will go with CUDA support disabled by the time being and revert back if they properly fix it.

Thank you again for all your help here.

**Comment by DeadSix27** [comment]
@4re Good to see you got it working though, that means it's not w2x's problem at least.

But this is only an issue on GCC7 or CUDA8, does CUDA9 + GCC7 work?

**Comment by 4re** [comment]
I have only tested it with `nvidia-cuda-toolkit-9.0.176` and `sys-devel/gcc-7.2.0` / `sys-devel/gcc-6.4.0`. All of them were having this problem and this changes fixed them.

I can test other combinations if you are interested.

**Comment by 4re** [comment]
Note that to use GCC7 with CUDA9 you need to patch CUDA9.

**Comment by DeadSix27** [comment]
Waifu2x will need the patches for cuda9, that's fine.

I'm just curious if there is a combination that does not require CUDA or GCC to be patched.

**Comment by 4re** [comment]
CUDA9 with =<GCC6 works without patching.

**Comment by DeadSix27** [comment]
@4re Did you come across any bug reports that can be linked here to see when it's fixed?

**Comment by 4re** [comment]
Ark maintainers are [patching CUDA SDK](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/cuda).

I don't know of any ticket related to this bug. If I find any I will link it here.

**Comment by sl1pkn07** [comment]
just note, is offtopic, but can help it.

with mxnet fail build if use certain GCC + CUDA

with

cuda 9.1.85.3 build OK with GCC 5.4.1 and GCC 6.3.1, but fails with GCC 5.5.0, GCC 6.4.1, and GCC 7.3.1

the same code with

cuda 9.2.88.1 build OK with GCC 7.3.1, and, in assumition, with GCC 5.4.1 and GCC 6.3.1

seems cuda needs use a certain GCC to work. the official list is:

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements

use other compiler than posted in the documentation can lead to fail
