### ISSUE TITLE
Commit 557829e breaks writing image

### ISSUE THREAD

**Issue by Kattus** [DeadSix27/waifu2x-converter-cpp#211]
Broken from 557829ed1fe556a39d048a0e652fbbed1cecc6b5 and beyond, while I did say it worked fine, more commits were added afterwards so the problem's most likely somewhere in there.
```
~/Desktop » waifu2x-converter-cpp --log-level 1 --input 78156819_p0.jpg                    
CUDA: GeForce GTX 1080
Processing file [1/1] "/home/katt/Desktop/78156819_p0.jpg": OpenCV(4.1.2) /build/opencv/src/opencv-4.1.2/modules/imgcodecs/src/loadsave.cpp:661: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'

Done, took: 0s total, file: 1.160s avg: 1.832s
Finished processing 1 files, took: 1.832secs total, filter: 0.937secs; 0 files skipped, 1 files errored. [GFLOPS: 1173.63, GFLOPS-Filter: 2293.80]
```

Compiled with:
GNU 9.2.0, OpenCV 4.1.2, OpenCL 2.2

**Comment by DeadSix27** [comment]
Most likely: https://github.com/DeadSix27/waifu2x-converter-cpp/pull/207/commits/f1254cf5b18a3cf150c7e36afc693bdd243cae46

@YukihoAA

**Comment by DeadSix27** [comment]
Also, doesn't affect windows.

**Comment by YukihoAA** [comment]
ok added 9b85e70 will fine

**Comment by DeadSix27** [comment]
@Kattus Feel free to test it.
